# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' boolean to check OpenMP exists
#' 
checkOpenMP <- function() {
    .Call('_N2R_checkOpenMP', PACKAGE = 'N2R')
}

n2Knn <- function(m, k, nThreads = 10L, verbose = TRUE, indexType = "angular", M = 12L, MaxM0 = 24L, ef_search_multiplier = 50, quiet = FALSE) {
    .Call('_N2R_n2Knn', PACKAGE = 'N2R', m, k, nThreads, verbose, indexType, M, MaxM0, ef_search_multiplier, quiet)
}

n2CrossKnn <- function(mA, mB, k, nThreads = 10L, verbose = TRUE, indexType = "angular", M = 12L, MaxM0 = 24L, ef_search_multiplier = 50, quiet = FALSE) {
    .Call('_N2R_n2CrossKnn', PACKAGE = 'N2R', mA, mB, k, nThreads, verbose, indexType, M, MaxM0, ef_search_multiplier, quiet)
}

