# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' boolean to check OpenMP exists
#' 
#' @export
checkOpenMP <- function() {
    .Call('_n2R_checkOpenMP', PACKAGE = 'n2R')
}

#' k-nn using n2 (approximate nearest neighbor)
#' 
#' @param m matrix i.e. Rcpp::NumericMatrix
#' @param k int
#' @param nThreads integer (default=10)
#' @param verbose boolean (default=FALSE)
#' @param indexType string (default="angular")
#' @param M integer (default=12)
#' @param MaxM0 integer (default=24)
#' @param ef_search_multiplier numeric (default=50)
#' @param quiet boolean (default=FALSE)
#' @export
n2Knn <- function(m, k, nThreads = 10L, verbose = TRUE, indexType = "angular", M = 12L, MaxM0 = 24L, ef_search_multiplier = 50, quiet = FALSE) {
    .Call('_n2R_n2Knn', PACKAGE = 'n2R', m, k, nThreads, verbose, indexType, M, MaxM0, ef_search_multiplier, quiet)
}

#' find NN of A in B
#'
#' @param mA matrix i.e. Rcpp::NumericMatrix
#' @param mB matrix i.e. Rcpp::NumericMatrix
#' @param k int
#' @param nThreads integer (default=10)
#' @param verbose boolean (default=FALSE)
#' @param indexType string (default="angular")
#' @param M integer (default=12)
#' @param MaxM0 integer (default=24)
#' @param ef_search_multiplier numeric (default=50)
#' @param quiet boolean (default=FALSE)
#' @export
n2CrossKnn <- function(mA, mB, k, nThreads = 10L, verbose = TRUE, indexType = "angular", M = 12L, MaxM0 = 24L, ef_search_multiplier = 50, quiet = FALSE) {
    .Call('_n2R_n2CrossKnn', PACKAGE = 'n2R', mA, mB, k, nThreads, verbose, indexType, M, MaxM0, ef_search_multiplier, quiet)
}

